### ISSUE TITLE
Query: Linux Implementation

### ISSUE THREAD

**Issue by d3vC0mm4nd3rShadowSlayer29** [ChrisFeline/ToNSaveManager#44]
I would like to ask on how to use this Save manager using Linux, particularly Steam OS.
I have tried emulating it but somehow I didn't make it work properly. You might either have tried making it work using it and would like to ask how? If not, it's okay, no pressure but would like to ask if there's a possibility that there's a development path for it.

**Comment by ChrisFeline** [comment]
Honestly I am not sure. I don't own a Steam deck or use a Linux distribution at the moment. So testing would be a little bit difficult.

I am guessing that VRChat writes log files to a different location within the emulated environment.

**Comment by d3vC0mm4nd3rShadowSlayer29** [comment]
Oooh. No worries. I didn't know, my apologies.
Okie dokie. I will try to check it on my end on how the data is saved and I'll share it with you to help you out. :3

**Comment by ChrisFeline** [comment]
I might revisit this issue in the future, for now is not a priority.

**Comment by AnriEvs** [comment]
Could this be fixed by allowing people to choose where the logging file is?

**Comment by ChrisFeline** [comment]
Honestly, I am not entirely sure.
The main problem is that Windows Forms does not compile for Linux.

**Comment by sageyx2002** [comment]
> Could this be fixed by allowing people to choose where the logging file is?

You could technically try running it with Wine. If that works, maybe that's a good half-temporary fix for everyone running Linux, as the app would more or less have to be rebuild from ground up (functions can mostly just move over) to address this issue.

**Comment by ChrisFeline** [comment]
I might rewrite this app's UI on a different framework sometime after my break.
It would take me a long time tho because there's so many things to take into account, and some endpoints I am using internally are Windows only.

**Comment by Yochyo** [comment]
I don't know if it helps, but the UI works on linux using proton experimental. Saving the game or even detecting it does not seem to have worked tho

![Image](https://github.com/user-attachments/assets/e37c8d80-ed03-4d51-96d8-a19f21e408cb)

**Comment by Yochyo** [comment]
The change would be relatively minor. All you'd have to do is to optionally read the "LocalApplicationData" Folder from an environment variable if it is set inside `GetVRChatDataLocation()`. As I couldn't get the code to compile on linux (and do not have a windows vm right now), here's a temporary solution (that actually works pretty well).

Just replace the placeholders and run the following command.

> user: is the name of your user (I know, quite obvious)

> appid: The appid of VRChat, you can find it by right clicking vrchat in steam under Properties -> Updates -> App ID

> proton: I had to use proton experimental ("Proton - Experimental"). If you don't have it installed, you can do that by selecting it by right clicking vrchat in steam under Properties -> Compatibility -> Force the use of a specific steam play compatibility tool

> path-to-executable: the path to the .exe you downloaded

```bash
STEAM_COMPAT_DATA_PATH="/home/<user>/.steam/steam/steamapps/compatdata/<appid>" \
STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/<user>/.steam/steam"  \
"/home/<user>/.steam/steam/steamapps/common/<proton>/proton" \
run "<path-to-executable>"
```

If you are using steam flatpak, changed the steam installation path or installed VRChat in a custom SteamLibrary, you might need to make small changes to the script

![Image](https://github.com/user-attachments/assets/61d6145e-5b76-4ead-abf8-b84a71fae4ef)

**Comment by ChrisFeline** [comment]
Interesting approach, do you have a link to documentation about environment variables for this?

**Comment by 69MichelleDB** [comment]
I just did a quick test (Arch, KDE-Plasma) using GE-Proton9-27 with Yochyo's variables, the basic functionality to read, store and copy codes work, OSC calls work too, there's just a small graphical issue where the emojies before the date don't show.
The two things I found that throw an exception are right clicking, which is a hard crash:
```
---------------------------
APP STARTUP FAILED!
---------------------------
System.ComponentModel.Win32Exception (0x80004005): Failed to get thread's DpiAwareness context.
   at System.Windows.Forms.DpiHelper.DpiAwarenessScope..ctor(DPI_AWARENESS_CONTEXT context, DPI_HOSTING_BEHAVIOR behavior)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.PreFilterMessage(Message& m)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.Microsoft.Office.IMsoComponent.FPreTranslateMessage(MSG* msg)
   at System.Windows.Forms.Application.ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at ToNSaveManager.Program.Main(String[] args)
---------------------------
OK   
---------------------------
```
And enabling the WebSocket API which throws an unhandled exception:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.HttpListenerException (120): Call not implemented.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at WatsonWebsocket.WatsonWsServer.Start()
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
ToNSaveManager
    Assembly Version: 2025.4.2.224
    Location: 
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Data.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Jint
    Assembly Version: 4.0.2.0
    Location: 
----------------------------------------
Acornima
    Assembly Version: 1.1.0.0
    Location: 
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Location: 
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Sockets
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Http
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Security
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.NameResolution
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
DiscordRPC
    Assembly Version: 1.2.1.24
    Location: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Location: 
----------------------------------------
System.Windows.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
WatsonWebsocket
    Assembly Version: 4.1.2.0
    Location: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Text.Json
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.HttpListener
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------

************** JIT Debugging **************
```

If you need people to test builds if you ever decide to pick this issue back up I'm down to help~

**Comment by ChrisFeline** [comment]
Both of these exceptions are not from the source code, I don't know If I can do much about them other than coding a possible alternative.

**Comment by Yochyo** [comment]
I gave up getting the Websocket API to work at some points, cause I had to dualboot for a few things anyway and use windows when playing ToN now. 

If you figure out how to get it to work, feel free to share ☺️. If I had to guess, you would probably have to install .net in the wineprefix?

I wrote a simple script that automates the process from my last comment. Feel free to use it and tell me if something does not work as expected :)
https://github.com/Yochyo/ToNSaveManagerLinux

**Comment by 69MichelleDB** [comment]
Yeh, that works fine as if just running the previous console code, sadly both exceptions from before still happen.
Since I'll be taking a short break from working on my solution to store codes on Linux, I'll see if I poke around with wine and can get around those errors.

**Comment by Kieaer** [comment]
Cannot run ToN save manager with current UI Framework
May be need convert UI framework to Avalonia UI, a cross-platform ui framework.
I'll try this

**Comment by wundervrc** [comment]
Got the the program working by using proton tricks.
Haven't tested it much but it appears to read the logs fine and it's saving the files needed in the prefix.
Can either do it with gui in proton tricks or via script: (Change path to where the file is)

#!/bin/bash
protontricks -c 'wine ~/wunderVRStuffs/ToN/ToNSaveManager.exe' 438100

**Comment by RonnieTiger** [comment]
> Got the the program working by using proton tricks. Haven't tested it much but it appears to read the logs fine and it's saving the files needed in the prefix. Can either do it with gui in proton tricks or via script: (Change path to where the file is)
> 
> #!/bin/bash protontricks -c 'wine ~/wunderVRStuffs/ToN/ToNSaveManager.exe' 438100

Just tested, this works for me too.

**Comment by Rainerthewolf** [comment]
> Got the the program working by using proton tricks. Haven't tested it much but it appears to read the logs fine and it's saving the files needed in the prefix. Can either do it with gui in proton tricks or via script: (Change path to where the file is)
> 
> #!/bin/bash protontricks -c 'wine ~/wunderVRStuffs/ToN/ToNSaveManager.exe' 438100

This still works for me

**Comment by Rainerthewolf** [comment]
I was able to get ToNSaveManager to launch from the start menu using a .desktop file.

1. Install protontricks and wine and icoutils if you haven’t already.
2. Extract an icon for ToNSaveManager using wrestool -x -t 14 ToNSaveManager.exe > ToNSaveManager.ico then convert it to a .png
3. Create a ToNSaveManager.desktop file at ~/.local/share/applications/
4. Set the following lines in the .desktop file
[Desktop Entry]
Version=1.0
Name=ToNSaveManager
Comment=ToNSaveManager
Exec=protontricks -c 'wine ~/ToN/ToNSaveManager.exe' 438100
Path=~/ToN/
Icon=~/ToN/ToNSaveManager.png
Terminal=false
Type=Application
Categories=Application;
5. You may need to make the .desktop file executable: chmod +x ~/home/ToN/ToNSaveManager.desktop
6. Save the .desktop file and it should appear in the start menu automatically

At this point, it should just work
